import Foundation

public enum PasteboardSemanticType {
    public static let concealed = "org.nspasteboard.ConcealedType"
    public static let transient = "org.nspasteboard.TransientType"
    public static let automaticallyGenerated = "org.nspasteboard.AutoGeneratedType"

    public static let privacySensitiveTypes: Set<String> = [
        concealed,
        transient,
        automaticallyGenerated,
    ]
}

public struct CapturePolicy: Codable, Equatable, Sendable {
    public var isCaptureEnabled: Bool
    public private(set) var excludedApplicationBundleIdentifiers: Set<String>
    public private(set) var ignoredPasteboardTypeIdentifiers: Set<String>

    public init(
        isCaptureEnabled: Bool = true,
        excludedApplicationBundleIdentifiers: Set<String> = [],
        ignoredPasteboardTypeIdentifiers: Set<String> = PasteboardSemanticType.privacySensitiveTypes
    ) {
        self.isCaptureEnabled = isCaptureEnabled
        self.excludedApplicationBundleIdentifiers = Set(
            excludedApplicationBundleIdentifiers.map(Self.normalizeBundleIdentifier)
        )
        self.ignoredPasteboardTypeIdentifiers = ignoredPasteboardTypeIdentifiers
            .union(PasteboardSemanticType.privacySensitiveTypes)
    }

    private enum CodingKeys: String, CodingKey {
        case isCaptureEnabled
        case excludedApplicationBundleIdentifiers
        case ignoredPasteboardTypeIdentifiers
    }

    public init(from decoder: any Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.init(
            isCaptureEnabled: try container.decode(Bool.self, forKey: .isCaptureEnabled),
            excludedApplicationBundleIdentifiers: try container.decode(
                Set<String>.self,
                forKey: .excludedApplicationBundleIdentifiers
            ),
            ignoredPasteboardTypeIdentifiers: try container.decode(
                Set<String>.self,
                forKey: .ignoredPasteboardTypeIdentifiers
            )
        )
    }

    public func decision(for candidate: CaptureCandidate) -> CaptureDecision {
        guard isCaptureEnabled else {
            return .reject(.capturePaused)
        }

        if let bundleIdentifier = candidate.sourceApplicationBundleIdentifier,
           excludedApplicationBundleIdentifiers.contains(Self.normalizeBundleIdentifier(bundleIdentifier))
        {
            return .reject(.applicationExcluded)
        }

        let ignoredTypes = ignoredPasteboardTypeIdentifiers
            .union(PasteboardSemanticType.privacySensitiveTypes)
        if !candidate.pasteboardTypeIdentifiers.isDisjoint(with: ignoredTypes) {
            return .reject(.concealedOrTransientType)
        }

        return .accept
    }

    public mutating func setApplication(_ bundleIdentifier: String, excluded: Bool) {
        let identifier = Self.normalizeBundleIdentifier(bundleIdentifier)
        guard !identifier.isEmpty else { return }
        if excluded {
            excludedApplicationBundleIdentifiers.insert(identifier)
        } else {
            excludedApplicationBundleIdentifiers.remove(identifier)
        }
    }

    private static func normalizeBundleIdentifier(_ bundleIdentifier: String) -> String {
        bundleIdentifier.trimmingCharacters(in: .whitespacesAndNewlines).lowercased()
    }
}

public struct CaptureCandidate: Equatable, Sendable {
    public let content: ClipContent
    public let sourceApplicationBundleIdentifier: String?
    public let originatingDeviceIdentifier: String?
    public let captureContext: ClipCaptureContext?
    public let sensitivity: ClipSensitivityMetadata?
    public let pasteboardTypeIdentifiers: Set<String>
    public let capturedAt: Date

    public init(
        content: ClipContent,
        sourceApplicationBundleIdentifier: String? = nil,
        originatingDeviceIdentifier: String? = nil,
        captureContext: ClipCaptureContext? = nil,
        sensitivity: ClipSensitivityMetadata? = nil,
        pasteboardTypeIdentifiers: Set<String> = [],
        capturedAt: Date = Date()
    ) {
        self.content = content
        self.sourceApplicationBundleIdentifier = sourceApplicationBundleIdentifier
        self.originatingDeviceIdentifier = originatingDeviceIdentifier
        self.captureContext = captureContext
        self.sensitivity = sensitivity
        self.pasteboardTypeIdentifiers = pasteboardTypeIdentifiers
        self.capturedAt = capturedAt
    }
}

public enum CaptureRejectionReason: String, Codable, Equatable, Sendable {
    case capturePaused
    case applicationExcluded
    case concealedOrTransientType
}

public enum CaptureDecision: Equatable, Sendable {
    case accept
    case reject(CaptureRejectionReason)
}

public enum CaptureOutcome: Equatable, Sendable {
    case inserted(HistoryItem)
    case refreshedDuplicate(HistoryItem)
    case ignored(CaptureRejectionReason)
}
